import type { WordData } from '../types/game';

export const wordList: WordData[] = [
  // --- COMPUTER & SOFTWARE (50) ---
  { word: "HARDWARE", hint: "The physical components of a computer system" },
  { word: "SOFTWARE", hint: "Programs and operating information used by a computer" },
  { word: "KEYBOARD", hint: "An input device used to type into a computer" },
  { word: "MONITOR", hint: "An output device that displays information in pictorial form" },
  { word: "MOUSE", hint: "A hand-held pointing device that detects two-dimensional motion" },
  { word: "MOTHERBOARD", hint: "The main printed circuit board in general-purpose computers" },
  { word: "PROCESSOR", hint: "The electronic circuitry that executes instructions" },
  { word: "MEMORY", hint: "The system that stores data for immediate use in a computer" },
  { word: "FIREWALL", hint: "A network security system that monitors traffic" },
  { word: "INTERNET", hint: "The global system of interconnected computer networks" },
  { word: "BROWSER", hint: "A software application for accessing the World Wide Web" },
  { word: "SERVER", hint: "A piece of computer hardware or software that provides functionality for other programs" },
  { word: "ROUTER", hint: "A networking device that forwards data packets between computer networks" },
  { word: "NETWORK", hint: "A collection of computers and devices connected together" },
  { word: "DATABASE", hint: "An organized collection of data stored and accessed electronically" },
  { word: "PASSWORD", hint: "A secret word or phrase used to gain admission to something" },
  { word: "MALWARE", hint: "Software that is intentionally designed to cause damage to a computer, server, or computer network" },
  { word: "VIRUS", hint: "A type of malicious software that propagates by inserting a copy of itself into another program" },
  { word: "ANTIVIRUS", hint: "Computer software used to prevent, detect, and remove malicious software" },
  { word: "ENCRYPTION", hint: "The process of encoding a message or information" },
  { word: "OPERATING", hint: "The main system software (first word) managing computer hardware" },
  { word: "TERMINAL", hint: "A text-based interface for the computer" },
  { word: "COMMAND", hint: "An instruction given to a computer program to perform a specific task" },
  { word: "PIXEL", hint: "The smallest controllable element of a picture represented on the screen" },
  { word: "RESOLUTION", hint: "The number of distinct pixels in each dimension that can be displayed" },
  { word: "STORAGE", hint: "A mechanism that enables a computer to retain data" },
  { word: "BACKUP", hint: "A copy of computer data taken and stored elsewhere" },
  { word: "PROTOCOL", hint: "A set of rules governing the exchange or transmission of data" },
  { word: "DOMAIN", hint: "The name of a website that serves as an address" },
  { word: "HOSTING", hint: "A service that allows organizations and individuals to post a website" },
  { word: "COMPILER", hint: "A program that translates computer code from one programming language to another" },
  { word: "ALGORITHM", hint: "A finite sequence of well-defined, computer-implementable instructions" },
  { word: "CACHE", hint: "A hardware or software component that stores data so that future requests can be served faster" },
  { word: "COOKIE", hint: "A small piece of data stored on the user's computer by the web browser" },
  { word: "BANDWIDTH", hint: "The maximum rate of data transfer across a given path" },
  { word: "LATENCY", hint: "The delay before a transfer of data begins following an instruction" },
  { word: "DESKTOP", hint: "A personal computer designed for regular use at a single location" },
  { word: "LAPTOP", hint: "A small, portable personal computer" },
  { word: "TABLET", hint: "A mobile device, typically with a mobile operating system and touchscreen display" },
  { word: "SMARTPHONE", hint: "A portable device that combines mobile telephone and computing functions" },
  { word: "PRINTER", hint: "A peripheral device which makes a persistent representation of graphics or text on paper" },
  { word: "SCANNER", hint: "A device that optically scans images, printed text, handwriting or an object" },
  { word: "USB", hint: "Industry standard that establishes specifications for cables and connectors" },
  { word: "BLUETOOTH", hint: "A short-range wireless technology standard" },
  { word: "ETHERNET", hint: "A family of wired computer networking technologies" },
  { word: "MAINFRAME", hint: "Computers primarily used by large organizations for critical applications" },
  { word: "VIRTUALIZATION", hint: "The act of creating a virtual version of something, including virtual computer hardware" },
  { word: "CLOUD", hint: "Servers that are accessed over the Internet" },
  { word: "DEPLOYMENT", hint: "All of the activities that make a software system available for use" },
  { word: "REPOSITORY", hint: "A central file storage location" },

  // --- GENERAL LIFE (25) ---
  { word: "FAMILY", hint: "A group of one or more parents and their children" },
  { word: "FRIEND", hint: "A person whom one knows and with whom one has a bond of mutual affection" },
  { word: "HOUSE", hint: "A building for human habitation" },
  { word: "MONEY", hint: "A current medium of exchange in the form of coins and banknotes" },
  { word: "WORK", hint: "Activity involving mental or physical effort done in order to achieve a purpose" },
  { word: "HOLIDAY", hint: "An extended period of leisure and recreation" },
  { word: "VACATION", hint: "A fixed holiday period" },
  { word: "MORNING", hint: "The period of time between midnight and noon" },
  { word: "EVENING", hint: "The period of time at the end of the day" },
  { word: "WEATHER", hint: "The state of the atmosphere at a place and time" },
  { word: "CLIMATE", hint: "The weather conditions prevailing in an area in general or over a long period" },
  { word: "TRANSPORTATION", hint: "The action of moving someone or something from a place to another" },
  { word: "EDUCATION", hint: "The process of receiving or giving systematic instruction" },
  { word: "KNOWLEDGE", hint: "Facts, information, and skills acquired through experience or education" },
  { word: "EXPERIENCE", hint: "Practical contact with and observation of facts or events" },
  { word: "HAPPINESS", hint: "The state of feeling or showing pleasure or contentment" },
  { word: "JOURNEY", hint: "An act of traveling from one place to another" },
  { word: "DESTINATION", hint: "The place to which someone or something is going or being sent" },
  { word: "ADVENTURE", hint: "An unusual and exciting, typically hazardous, experience or activity" },
  { word: "ROUTINE", hint: "A sequence of actions regularly followed" },
  { word: "HEALTH", hint: "The state of being free from illness or injury" },
  { word: "MEDICINE", hint: "The science or practice of the diagnosis, treatment, and prevention of disease" },
  { word: "HOSPITAL", hint: "An institution providing medical and surgical treatment" },
  { word: "GROCERY", hint: "Items of food sold in a supermarket" },
  { word: "SHOPPING", hint: "The purchasing of goods from stores" },

  // --- SPORTS (10) ---
  { word: "FOOTBALL", hint: "A game involving two teams passing a ball across a field" },
  { word: "BASKETBALL", hint: "A game played between two teams of five players in which goals are scored by throwing a ball through a netted hoop" },
  { word: "BASEBALL", hint: "A ball game played between two teams of nine on a diamond-shaped circuit" },
  { word: "TENNIS", hint: "A game in which two or four players strike a ball with rackets over a net stretched across a court" },
  { word: "SOCCER", hint: "A game played by two teams of eleven players with a spherical ball that may not be touched with the hands or arms" },
  { word: "VOLLEYBALL", hint: "A game for two teams, usually of six players, in which a large ball is hit by hand over a high net" },
  { word: "CRICKET", hint: "An open-air game played on a large grass field with ball, bats, and two wickets" },
  { word: "RUGBY", hint: "A team game played with an oval ball that may be kicked, carried, and passed from hand to hand" },
  { word: "SWIMMING", hint: "The sport or activity of propelling oneself through water using the limbs" },
  { word: "ATHLETICS", hint: "The sport of competing in track and field events" },

  // --- CODING (10) ---
  { word: "JAVASCRIPT", hint: "The programming language of the Web" },
  { word: "TYPESCRIPT", hint: "JavaScript with syntax for types" },
  { word: "PYTHON", hint: "A high-level, interpreted conceptual programming language" },
  { word: "JAVA", hint: "A high-level, class-based, object-oriented programming language" },
  { word: "VARIABLE", hint: "A storage location paired with an associated symbolic name" },
  { word: "FUNCTION", hint: "A block of code designed to perform a particular task" },
  { word: "COMPONENT", hint: "An independent, reusable piece of a User Interface" },
  { word: "FRAMEWORK", hint: "An abstraction in which software providing generic functionality can be selectively changed" },
  { word: "LIBRARY", hint: "A collection of non-volatile resources used by computer programs" },
  { word: "DEBUGGING", hint: "The process of identifying and removing errors from computer hardware or software" },
  
  // --- EXTRA CODING (5) ---
  { word: "SYNTAX", hint: "The set of rules that defines the combinations of symbols that are considered to be correctly structured" },
  { word: "ITERATION", hint: "The repetition of a process in order to generate an outcome" },
  { word: "RECURSION", hint: "When a function calls itself directly or indirectly" },
  { word: "INTERFACE", hint: "A shared boundary across which two or more separate components exchange information" },
  { word: "ASYNCHRONOUS", hint: "Events occurring independently of the main program flow" },

  // --- FOOD (15) ---
  { word: "PIZZA", hint: "A dish of Italian origin consisting of a usually round, flat base of leavened wheat-based dough" },
  { word: "BURGER", hint: "A dish consisting of fillings—usually a patty of ground meat—placed inside a sliced bun" },
  { word: "PASTA", hint: "A type of food typically made from an unleavened dough of wheat flour mixed with water or eggs" },
  { word: "SALAD", hint: "A dish consisting of mixed, mostly natural ingredients with at least one raw ingredient" },
  { word: "SANDWICH", hint: "A food typically consisting of vegetables, sliced cheese or meat, placed on or between slices of bread" },
  { word: "SUSHI", hint: "A Japanese dish of prepared vinegared rice, usually with some sugar and salt, accompanying a variety of ingredients" },
  { word: "CHOCOLATE", hint: "A preparation of roasted and ground cacao seeds that is made in the form of a liquid, paste, or in a block" },
  { word: "CHEESE", hint: "A dairy product derived from milk that is produced in a wide range of flavors, textures, and forms" },
  { word: "BREAD", hint: "A staple food prepared from a dough of flour and water, usually by baking" },
  { word: "BUTTER", hint: "A dairy product made from the fat and protein components of churned cream" },
  { word: "CHICKEN", hint: "A type of domesticated fowl, a subspecies of the red junglefowl" },
  { word: "BEEF", hint: "The culinary name for meat from cattle" },
  { word: "VEGETABLE", hint: "Parts of plants that are consumed by humans or other animals as food" },
  { word: "FRUIT", hint: "The seed-bearing structure in flowering plants formed from the ovary after flowering" },
  { word: "DESSERT", hint: "A course that concludes a meal, usually consisting of sweet foods" },

  // --- SCIENCE (10) ---
  { word: "PHYSICS", hint: "The natural science that studies matter, its fundamental constituents, its motion and behavior through space and time" },
  { word: "CHEMISTRY", hint: "The scientific study of the properties and behavior of matter" },
  { word: "BIOLOGY", hint: "The scientific study of life" },
  { word: "ASTRONOMY", hint: "The study of everything in the universe beyond Earth's atmosphere" },
  { word: "GRAVITY", hint: "The fundamental interaction which causes mutual attraction between all things that have mass" },
  { word: "MOLECULE", hint: "An electrically neutral group of two or more atoms held together by chemical bonds" },
  { word: "ATOM", hint: "The basic building block of chemistry" },
  { word: "ELECTRON", hint: "A subatomic particle with a negative one elementary electric charge" },
  { word: "PLANET", hint: "A large astronomical body that is neither a star nor a stellar remnant" },
  { word: "GALAXY", hint: "A gravitationally bound system of stars, stellar remnants, interstellar gas, dust, and dark matter" },
  
  // --- EXTRA SCIENCE & NATURE (25) ---
  { word: "UNIVERSE", hint: "All of space and time and their contents" },
  { word: "EVOLUTION", hint: "Change in the heritable characteristics of biological populations over successive generations" },
  { word: "GENETICS", hint: "The branch of biology concerned with the study of genes, genetic variation, and heredity in organisms" },
  { word: "CELL", hint: "The basic structural, functional, and biological unit of all known organisms" },
  { word: "ORGANISM", hint: "Any individual entity that embodies the properties of life" },
  { word: "MOUNTAIN", hint: "An elevated portion of the Earth's crust, generally with steep sides that show significant exposed bedrock" },
  { word: "OCEAN", hint: "A body of water that composes much of a planet's hydrosphere" },
  { word: "FOREST", hint: "A large area dominated by trees" },
  { word: "DESERT", hint: "A barren area of landscape where little precipitation occurs" },
  { word: "RIVER", hint: "A natural flowing watercourse, usually freshwater, flowing towards an ocean, sea, lake or another river" },
  { word: "CANYON", hint: "A deep cleft between escarpments or cliffs" },
  { word: "VOLCANO", hint: "A rupture in the crust of a planetary-mass object, such as Earth, that allows hot lava, volcanic ash, and gases to escape" },
  { word: "ISLAND", hint: "A piece of sub-continental land that is surrounded by water" },
  { word: "CONTINENT", hint: "One of several very large landmasses" },
  { word: "COUNTRY", hint: "A distinct territorial body or political entity" },
  { word: "CITY", hint: "A large human settlement" },
  { word: "VILLAGE", hint: "A clustered human settlement or community, larger than a hamlet but smaller than a town" },
  { word: "SOCIETY", hint: "A group of individuals involved in persistent social interaction" },
  { word: "CULTURE", hint: "The social behavior, institutions, and norms found in human societies" },
  { word: "HISTORY", hint: "The study of the past" },
  { word: "GEOGRAPHY", hint: "A field of science devoted to the study of the lands, features, inhabitants, and phenomena of Earth" },
  { word: "MATHEMATICS", hint: "The abstract study of numbers, quantity, structure, relations, etc." },
  { word: "LITERATURE", hint: "Written works, especially those considered of superior or lasting artistic merit" },
  { word: "PHILOSOPHY", hint: "The study of general and fundamental questions" },
  { word: "PSYCHOLOGY", hint: "The scientific study of mind and behavior" }
];
